export const JOB_TITLES: string[] = [
  // Technologie & IT
  'Software Developer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Data Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'Cybersecurity Analyst',
  'Informatiebeveiliging Specialist',
  'IT-beheerder',
  'Systeembeheerder',
  'Netwerkbeheerder',
  'Applicatiebeheerder',
  'Informatiebeheerder',
  'Informatiemanager',
  'Functioneel Beheerder',
  'Technisch Beheerder',
  'IT-projectmanager',
  'Scrum Master',
  'Product Owner',
  'UX Designer',
  'UI Designer',
  'Grafisch Ontwerper',
  'Web Designer',
  'Business Analist',
  'Data Analist',
  'BI Developer',
  'Testmanager',
  'QA Engineer',
  'Software Architect',
  'Solution Architect',
  'Tech Lead',
  'CTO',
  'IT Manager',
  'Helpdesk Medewerker',
  'Support Engineer',

  // Zorg & Welzijn
  'Verpleegkundige',
  'Verzorgende IG',
  'Zorgassistent',
  'Doktersassistent',
  'Arts',
  'Huisarts',
  'Specialist',
  'Tandarts',
  'Fysiotherapeut',
  'Ergotherapeut',
  'Logopedist',
  'Psycholoog',
  'Psychiater',
  'GGZ-medewerker',
  'Maatschappelijk Werker',
  'Jeugdzorgwerker',
  'Begeleider',
  'Thuiszorgmedewerker',
  'Verloskundige',
  'Apotheker',
  'Optometrist',
  'Diëtist',
  'Sportcoach',
  'Personal Trainer',

  // Onderwijs & Pedagogiek
  'Leraar Basisonderwijs',
  'Leraar Voortgezet Onderwijs',
  'Docent MBO',
  'Docent HBO',
  'Universitair Docent',
  'Onderwijsassistent',
  'Intern Begeleider',
  'Schooldirecteur',
  'Pedagoog',
  'Orthopedagoog',
  'Kinderopvang Medewerker',
  'Pedagogisch Medewerker',
  'Trainer',
  'Coach',

  // Overheid & Beleid
  'Beleidsmedewerker',
  'Beleidsadviseur',
  'Projectleider',
  'Projectmanager',
  'Programmamanager',
  'Adviseur',
  'Consultant',
  'Gemeenteambtenaar',
  'Handhaver',
  'Inspecteur',
  'Juridisch Adviseur',
  'Jurist',
  'Advocaat',
  'Notaris',
  'Paralegal',
  'Compliance Officer',
  'Legal Counsel',
  'Beleidsonderzoeker',

  // Finance & Economie
  'Accountant',
  'Registeraccountant',
  'Financieel Controller',
  'Financial Analyst',
  'Business Controller',
  'Boekhouder',
  'Administrateur',
  'Credit Manager',
  'Risk Manager',
  'Compliance Manager',
  'Actuaris',
  'Treasury Manager',
  'Inkoper',
  'Category Manager',

  // Marketing & Communicatie
  'Marketeer',
  'Marketing Manager',
  'Content Marketeer',
  'Content Creator',
  'Copywriter',
  'SEO Specialist',
  'SEA Specialist',
  'Social Media Manager',
  'Digital Marketeer',
  'Brand Manager',
  'PR Adviseur',
  'Communicatieadviseur',
  'Woordvoerder',
  'Journalist',
  'Redacteur',
  'Fotograaf',
  'Videograaf',

  // Sales & Commercie
  'Accountmanager',
  'Sales Manager',
  'Business Developer',
  'Key Account Manager',
  'Sales Representative',
  'Commercieel Medewerker',
  'Inside Sales',
  'Relatiemanager',
  'Verkoper',
  'Vastgoedmakelaar',
  'Hypotheekadviseur',
  'Financieel Adviseur',
  'Verzekeringsadviseur',

  // Logistiek & Supply Chain
  'Logistiek Manager',
  'Supply Chain Manager',
  'Planner',
  'Expediteur',
  'Magazijnmedewerker',
  'Chauffeur',
  'Inkoper',
  'Demand Planner',
  'Warehouse Manager',
  'Operations Manager',

  // Techniek & Bouw
  'Werktuigbouwkundig Ingenieur',
  'Elektrotechnisch Ingenieur',
  'Civiel Ingenieur',
  'Bouwkundig Ingenieur',
  'Constructeur',
  'Architect',
  'Stedenbouwkundige',
  'Uitvoerder',
  'Calculator',
  'Projectleider Bouw',
  'Installateur',
  'Monteur',
  'Servicetechnicus',
  'Onderhoudsmonteur',
  'Procesoperator',
  'Productiemedewerker',

  // HR & Organisatie
  'HR Adviseur',
  'HR Manager',
  'Recruiter',
  'Talent Acquisition Specialist',
  'Payroll Specialist',
  'L&D Specialist',
  'Organisatieadviseur',
  'Verandermanager',
  'HR Business Partner',

  // Klantservice & Administratie
  'Klantenservice Medewerker',
  'Customer Success Manager',
  'Callcenter Agent',
  'Receptionist',
  'Administratief Medewerker',
  'Office Manager',
  'Secretaresse',
  'Management Assistent',
  'Directiesecretaresse',

  // Management & Directie
  'Teamleider',
  'Afdelingsmanager',
  'Directeur',
  'Algemeen Directeur',
  'CEO',
  'CFO',
  'COO',
  'Interim Manager',
  'Managing Director',

  // Horeca & Retail
  'Kok',
  'Chef-kok',
  'Horecamanager',
  'Barista',
  'Filiaalmanager',
  'Merchandiser',
  'Visual Merchandiser',

  // Creatief & Cultuur
  'Kunstenaar',
  'Muzikant',
  'Acteur',
  'Regisseur',
  'Producent',
  'Curator',
  'Bibliotheekmedewerker',
  'Archivaris',
]
